runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /main\.css
  static_files: main.css
  upload: main\.css
- url: /.*
  script: main.app